// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: protomsg/field.proto

package protomsg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Array []*FieldLine `protobuf:"bytes,1000,rep,name=array,proto3" json:"array,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_field_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_field_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_protomsg_field_proto_rawDescGZIP(), []int{0}
}

func (x *Field) GetArray() []*FieldLine {
	if x != nil {
		return x.Array
	}
	return nil
}

type FieldLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field []int32 `protobuf:"varint,1000,rep,packed,name=field,proto3" json:"field,omitempty"`
}

func (x *FieldLine) Reset() {
	*x = FieldLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protomsg_field_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldLine) ProtoMessage() {}

func (x *FieldLine) ProtoReflect() protoreflect.Message {
	mi := &file_protomsg_field_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldLine.ProtoReflect.Descriptor instead.
func (*FieldLine) Descriptor() ([]byte, []int) {
	return file_protomsg_field_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FieldLine) GetField() []int32 {
	if x != nil {
		return x.Field
	}
	return nil
}

var File_protomsg_field_proto protoreflect.FileDescriptor

var file_protomsg_field_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67,
	0x22, 0x53, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x61, 0x72, 0x72,
	0x61, 0x79, 0x18, 0xe8, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x05, 0x61, 0x72, 0x72, 0x61, 0x79, 0x1a, 0x1d, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x15,
	0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0xe8, 0x07, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protomsg_field_proto_rawDescOnce sync.Once
	file_protomsg_field_proto_rawDescData = file_protomsg_field_proto_rawDesc
)

func file_protomsg_field_proto_rawDescGZIP() []byte {
	file_protomsg_field_proto_rawDescOnce.Do(func() {
		file_protomsg_field_proto_rawDescData = protoimpl.X.CompressGZIP(file_protomsg_field_proto_rawDescData)
	})
	return file_protomsg_field_proto_rawDescData
}

var file_protomsg_field_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protomsg_field_proto_goTypes = []interface{}{
	(*Field)(nil),     // 0: protomsg.field
	(*FieldLine)(nil), // 1: protomsg.field.line
}
var file_protomsg_field_proto_depIdxs = []int32{
	1, // 0: protomsg.field.array:type_name -> protomsg.field.line
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protomsg_field_proto_init() }
func file_protomsg_field_proto_init() {
	if File_protomsg_field_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protomsg_field_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protomsg_field_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protomsg_field_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protomsg_field_proto_goTypes,
		DependencyIndexes: file_protomsg_field_proto_depIdxs,
		MessageInfos:      file_protomsg_field_proto_msgTypes,
	}.Build()
	File_protomsg_field_proto = out.File
	file_protomsg_field_proto_rawDesc = nil
	file_protomsg_field_proto_goTypes = nil
	file_protomsg_field_proto_depIdxs = nil
}
